/**
 * connect4 API.
 * Documentation of our connect4 API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetGridResponseBody { 
    current_player_color: number;
    grid: Array<Array<number>>;
}

